language: python

# cache pip dependency
cache: pip

sudo: required

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - pypy3
install:
    - |
      pip install flake8 pytest
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
      if [ -f package.json ]; then npm install; fi
      if [ -f packages.txt ]; then cat packages.txt | xargs sudo apt-get install; fi
      pip install -r _building/building-requirements.txt
script:
    - sudo env "PATH=$PATH" python --version          # environment check
    - sudo env "PATH=$PATH" python -c 'import sys; print(sys.version)'           # environment check
    - sudo env "PATH=$PATH" python -c 'import sys; print(sys.version_info)'           # environment check

    # Enable debug log: UT_DEBUG=1
    - |

      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      cp setup.py ..
      cd ..
      python setup.py install
      cd -
      sudo env "PATH=$PATH:$(npm bin)" pytest -v

      make -C docs html

# after_success:
#   - pip install python-coveralls && coveralls
