language: python

# cache pip dependency
cache: pip

sudo: required

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - pypy3
install:
    - pip install -r requirements.txt
script:
    - sudo env "PATH=$PATH" python --version          # environment check
    - sudo env "PATH=$PATH" python -c 'import sys; print(sys.version)'           # environment check
    - sudo env "PATH=$PATH" python -c 'import sys; print(sys.version_info)'           # environment check

    # Enable debug log: UT_DEBUG=1
    - >-
        sudo env "PATH=$PATH" UT_DEBUG=0 PYTHONPATH="$(cd ..; pwd)" python -m unittest discover -c --failfast -s .

    - make -C docs html

# after_success:
#   - pip install python-coveralls && coveralls
